///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String fontsDUBAIBOLD = 'assets/fonts/DUBAI-BOLD.TTF';
  static const String fontsDUBAILIGHT = 'assets/fonts/DUBAI-LIGHT.TTF';
  static const String fontsDUBAIMEDIUM = 'assets/fonts/DUBAI-MEDIUM.TTF';
  static const String fontsDUBAIREGULAR = 'assets/fonts/DUBAI-REGULAR.TTF';
  static const String imagesAvatoop1 = 'assets/images/avatoop1.jpg';
  static const String imagesAvatoop2 = 'assets/images/avatoop2.jpg';
  static const String imagesAvatoop4 = 'assets/images/avatoop4.jpg';
  static const String imagesAvatoop5 = 'assets/images/avatoop5.jpg';
  static const String imagesAzadeganLeague = 'assets/images/azadegan_league.jpg';
  static const String imagesBartarLeague = 'assets/images/bartar_league.jpg';
  static const String imagesBundesligaLeague = 'assets/images/Bundesliga_league.png';
  static const String imagesDow = 'assets/images/dow.png';
  static const String imagesImg = 'assets/images/img.png';
  static const String imagesImg1 = 'assets/images/img_1.png';
  static const String imagesImg2 = 'assets/images/img_2.png';
  static const String imagesImg3 = 'assets/images/img_3.png';
  static const String imagesImg4 = 'assets/images/img_4.png';
  static const String imagesImg5 = 'assets/images/img_5.png';
  static const String imagesLaligaLeague = 'assets/images/laliga_league.png';
  static const String imagesLigue1 = 'assets/images/ligue_1.png';
  static const String imagesLoginPhoto = 'assets/images/loginPhoto.png';
  static const String imagesLoginpage = 'assets/images/loginpage.jpg';
  static const String imagesNos = 'assets/images/nos.png';
  static const String imagesPremierLeague = 'assets/images/premier_league.png';
  static const String imagesProfile = 'assets/images/profile.png';
  static const String imagesSeraieALeague = 'assets/images/seraie_a_league.jpg';
  static const String imagesSeria = 'assets/images/seria.png';
  static const String imagesUntitled = 'assets/images/Untitled.jpg';

}
